# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ssv_pb2 as ssv__pb2


class SSVStub(object):
    """Shared-Secret-Validator(SSV) API

    This API enables the communication between a validator client and an SSV node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTaskStream = channel.unary_stream(
                '/ethereum.eth.v1alpha1.SSV/GetTaskStream',
                request_serializer=ssv__pb2.StreamRequest.SerializeToString,
                response_deserializer=ssv__pb2.SSVTask.FromString,
                )


class SSVServicer(object):
    """Shared-Secret-Validator(SSV) API

    This API enables the communication between a validator client and an SSV node
    """

    def GetTaskStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SSVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTaskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTaskStream,
                    request_deserializer=ssv__pb2.StreamRequest.FromString,
                    response_serializer=ssv__pb2.SSVTask.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ethereum.eth.v1alpha1.SSV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SSV(object):
    """Shared-Secret-Validator(SSV) API

    This API enables the communication between a validator client and an SSV node
    """

    @staticmethod
    def GetTaskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ethereum.eth.v1alpha1.SSV/GetTaskStream',
            ssv__pb2.StreamRequest.SerializeToString,
            ssv__pb2.SSVTask.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
